image: repo.cfhn.it/infrastructure/gitlab/maven-docker
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean install
    - docker-compose build
    - docker-compose push
deploy:
  stage: deploy
  script:
    - docker-compose up -d