image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD repo.cfhn.it

build:
  stage: build
  script:
  - docker build -t repo.cfhn.it/mycfhn/login-ms/login-ms .
  - docker push repo.cfhn.it/mycfhn/login-ms/login-ms
